title: Victoria Agboola
email: gbemisolagboola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A Data Science graduate student's portfolio highlighting projects, skills, and industrial engineering insights.

url: "https://<Oluvicky>.github.io" # your GitHub Pages URL

theme: minima # This is a simple and straightforward theme, but you can change it to any theme you prefer

# Add theme-specific settings here. This varies by theme, so check your theme's documentation.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
