title: Victoria Agboola
email: gbemisolagboola@gmail.com
description: A Data Science graduate student's portfolio highlighting projects, skills, and industrial engineering insights.

url: "https://Oluvicky.github.io" # your GitHub Pages URL
theme: jekyll-theme-minimal # This is a simple and straightforward theme, but you can change it to any theme you prefer

